#!/bin/bash

#PBS -q medium
#PBS -l size=1200
#PBS -l walltime=16:00:00
#PBS -o /lustre/scratch/${USER}/cybershake/RuptureCodes/GenRand-mpi/test_scale.out
#PBS -e /lustre/scratch/${USER}/cybershake/RuptureCodes/GenRand-mpi/test_scale.err
#PBS -V
#PBS -A TG-MCA03S012

IOBUF_PARAMS='*:size=64M:count=4';export IOBUF_PARAMS;

echo "Job start"
date

cd /lustre/scratch/${USER}/cybershake/RuptureCodes/GenRand-mpi
aprun -n 1200 ./rupgen rupgen.conf

echo "Jobs done"
date
exit 0
