#!/bin/bash

#PBS -q small
#PBS -l size=300
#PBS -l walltime=0:30:00
#PBS -o /lustre/scratch/${USER}/cybershake/RuptureCodes/GenRand-mpi/test_scale.out
#PBS -e /lustre/scratch/${USER}/cybershake/RuptureCodes/GenRand-mpi/test_scale.err
#PBS -V
#PBS -A TG-MCA03S012

IOBUF_PARAMS='*:size=64M:count=4';export IOBUF_PARAMS;

echo "Job start"
date

mkdir ${RUPDIR}
mkdir ${LOGDIR}

cd /lustre/scratch/${USER}/cybershake/RuptureCodes/GenRand-mpi
aprun -n 300 ./rupgen rupgen.conf

echo "Jobs done"
date
exit 0
