package mapping;

// Generated Aug 9, 2007 12:13:49 AM by Hibernate Tools 3.2.0.b9

import java.util.HashSet;
import java.util.Set;

/**
 * CyberShakeSites generated by hbm2java
 */
public class CyberShakeSites implements java.io.Serializable {

	private int csSiteId;

	private String csSiteName;

	private String csShortName;

	private double csSiteLat;

	private double csSiteLon;

	private Set<CyberShakeSiteRegions> cyberShakeSiteRegionses = new HashSet<CyberShakeSiteRegions>(
			0);

	public CyberShakeSites() {
	}

	public CyberShakeSites(int csSiteId, String csSiteName, String csShortName,
			double csSiteLat, double csSiteLon) {
		this.csSiteId = csSiteId;
		this.csSiteName = csSiteName;
		this.csShortName = csShortName;
		this.csSiteLat = csSiteLat;
		this.csSiteLon = csSiteLon;
	}

	public CyberShakeSites(int csSiteId, String csSiteName, String csShortName,
			double csSiteLat, double csSiteLon,
			Set<CyberShakeSiteRegions> cyberShakeSiteRegionses) {
		this.csSiteId = csSiteId;
		this.csSiteName = csSiteName;
		this.csShortName = csShortName;
		this.csSiteLat = csSiteLat;
		this.csSiteLon = csSiteLon;
		this.cyberShakeSiteRegionses = cyberShakeSiteRegionses;
	}

	public int getCsSiteId() {
		return this.csSiteId;
	}

	public void setCsSiteId(int csSiteId) {
		this.csSiteId = csSiteId;
	}

	public String getCsSiteName() {
		return this.csSiteName;
	}

	public void setCsSiteName(String csSiteName) {
		this.csSiteName = csSiteName;
	}

	public String getCsShortName() {
		return this.csShortName;
	}

	public void setCsShortName(String csShortName) {
		this.csShortName = csShortName;
	}

	public double getCsSiteLat() {
		return this.csSiteLat;
	}

	public void setCsSiteLat(double csSiteLat) {
		this.csSiteLat = csSiteLat;
	}

	public double getCsSiteLon() {
		return this.csSiteLon;
	}

	public void setCsSiteLon(double csSiteLon) {
		this.csSiteLon = csSiteLon;
	}

	public Set<CyberShakeSiteRegions> getCyberShakeSiteRegionses() {
		return this.cyberShakeSiteRegionses;
	}

	public void setCyberShakeSiteRegionses(
			Set<CyberShakeSiteRegions> cyberShakeSiteRegionses) {
		this.cyberShakeSiteRegionses = cyberShakeSiteRegionses;
	}

}
