package mapping;

// Generated Aug 9, 2007 9:53:47 PM by Hibernate Tools 3.2.0.b9

/**
 * CyberShakeSiteRuptures generated by hbm2java
 */
public class CyberShakeSiteRuptures implements java.io.Serializable {

	private CyberShakeSiteRupturesId id;

	private CyberShakeSiteRegions cyberShakeSiteRegions;

	private ErfIds erfIds;

	private Ruptures ruptures;

	private CyberShakeSites cyberShakeSites;

	public CyberShakeSiteRuptures() {
	}

	public CyberShakeSiteRuptures(CyberShakeSiteRupturesId id,
			CyberShakeSiteRegions cyberShakeSiteRegions, ErfIds erfIds,
			Ruptures ruptures, CyberShakeSites cyberShakeSites) {
		this.id = id;
		this.cyberShakeSiteRegions = cyberShakeSiteRegions;
		this.erfIds = erfIds;
		this.ruptures = ruptures;
		this.cyberShakeSites = cyberShakeSites;
	}

	public CyberShakeSiteRupturesId getId() {
		return this.id;
	}

	public void setId(CyberShakeSiteRupturesId id) {
		this.id = id;
	}

	public CyberShakeSiteRegions getCyberShakeSiteRegions() {
		return this.cyberShakeSiteRegions;
	}

	public void setCyberShakeSiteRegions(
			CyberShakeSiteRegions cyberShakeSiteRegions) {
		this.cyberShakeSiteRegions = cyberShakeSiteRegions;
	}

	public ErfIds getErfIds() {
		return this.erfIds;
	}

	public void setErfIds(ErfIds erfIds) {
		this.erfIds = erfIds;
	}

	public Ruptures getRuptures() {
		return this.ruptures;
	}

	public void setRuptures(Ruptures ruptures) {
		this.ruptures = ruptures;
	}

	public CyberShakeSites getCyberShakeSites() {
		return this.cyberShakeSites;
	}

	public void setCyberShakeSites(CyberShakeSites cyberShakeSites) {
		this.cyberShakeSites = cyberShakeSites;
	}

}
