package mapping;

// Generated Aug 9, 2007 12:13:49 AM by Hibernate Tools 3.2.0.b9

/**
 * CyberShakeSiteRegionsId generated by hbm2java
 */
public class CyberShakeSiteRegionsId implements java.io.Serializable {

	private int csSiteId;

	private int erfId;

	private double cutoffDist;

	public CyberShakeSiteRegionsId() {
	}

	public CyberShakeSiteRegionsId(int csSiteId, int erfId, double cutoffDist) {
		this.csSiteId = csSiteId;
		this.erfId = erfId;
		this.cutoffDist = cutoffDist;
	}

	public int getCsSiteId() {
		return this.csSiteId;
	}

	public void setCsSiteId(int csSiteId) {
		this.csSiteId = csSiteId;
	}

	public int getErfId() {
		return this.erfId;
	}

	public void setErfId(int erfId) {
		this.erfId = erfId;
	}

	public double getCutoffDist() {
		return this.cutoffDist;
	}

	public void setCutoffDist(double cutoffDist) {
		this.cutoffDist = cutoffDist;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CyberShakeSiteRegionsId))
			return false;
		CyberShakeSiteRegionsId castOther = (CyberShakeSiteRegionsId) other;

		return (this.getCsSiteId() == castOther.getCsSiteId())
				&& (this.getErfId() == castOther.getErfId())
				&& (this.getCutoffDist() == castOther.getCutoffDist());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCsSiteId();
		result = 37 * result + this.getErfId();
		result = 37 * result + (int) this.getCutoffDist();
		return result;
	}

}
