package mapping;

// Generated Aug 9, 2007 9:53:47 PM by Hibernate Tools 3.2.0.b9

import java.util.HashSet;
import java.util.Set;

/**
 * CyberShakeSites generated by hbm2java
 */
public class CyberShakeSites implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6805059051797651454L;

	private int csSiteId;

	private String csSiteName;

	private String csShortName;

	private double csSiteLat;

	private double csSiteLon;

	private Set<CyberShakeSiteRuptures> cyberShakeSiteRuptureses = new HashSet<CyberShakeSiteRuptures>(
			0);

	private Set<CyberShakeSiteRegions> cyberShakeSiteRegionses = new HashSet<CyberShakeSiteRegions>(
			0);

	private Set<PeakAmplitudes> peakAmplitudeses = new HashSet<PeakAmplitudes>(
			0);

	public CyberShakeSites() {
	}

	public CyberShakeSites(int csSiteId, String csSiteName, String csShortName,
			double csSiteLat, double csSiteLon) {
		this.csSiteId = csSiteId;
		this.csSiteName = csSiteName;
		this.csShortName = csShortName;
		this.csSiteLat = csSiteLat;
		this.csSiteLon = csSiteLon;
	}

	public CyberShakeSites(int csSiteId, String csSiteName, String csShortName,
			double csSiteLat, double csSiteLon,
			Set<CyberShakeSiteRuptures> cyberShakeSiteRuptureses,
			Set<CyberShakeSiteRegions> cyberShakeSiteRegionses,
			Set<PeakAmplitudes> peakAmplitudeses) {
		this.csSiteId = csSiteId;
		this.csSiteName = csSiteName;
		this.csShortName = csShortName;
		this.csSiteLat = csSiteLat;
		this.csSiteLon = csSiteLon;
		this.cyberShakeSiteRuptureses = cyberShakeSiteRuptureses;
		this.cyberShakeSiteRegionses = cyberShakeSiteRegionses;
		this.peakAmplitudeses = peakAmplitudeses;
	}

	public int getCsSiteId() {
		return this.csSiteId;
	}

	public void setCsSiteId(int csSiteId) {
		this.csSiteId = csSiteId;
	}

	public String getCsSiteName() {
		return this.csSiteName;
	}

	public void setCsSiteName(String csSiteName) {
		this.csSiteName = csSiteName;
	}

	public String getCsShortName() {
		return this.csShortName;
	}

	public void setCsShortName(String csShortName) {
		this.csShortName = csShortName;
	}

	public double getCsSiteLat() {
		return this.csSiteLat;
	}

	public void setCsSiteLat(double csSiteLat) {
		this.csSiteLat = csSiteLat;
	}

	public double getCsSiteLon() {
		return this.csSiteLon;
	}

	public void setCsSiteLon(double csSiteLon) {
		this.csSiteLon = csSiteLon;
	}

	public Set<CyberShakeSiteRuptures> getCyberShakeSiteRuptureses() {
		return this.cyberShakeSiteRuptureses;
	}

	public void setCyberShakeSiteRuptureses(
			Set<CyberShakeSiteRuptures> cyberShakeSiteRuptureses) {
		this.cyberShakeSiteRuptureses = cyberShakeSiteRuptureses;
	}

	public Set<CyberShakeSiteRegions> getCyberShakeSiteRegionses() {
		return this.cyberShakeSiteRegionses;
	}

	public void setCyberShakeSiteRegionses(
			Set<CyberShakeSiteRegions> cyberShakeSiteRegionses) {
		this.cyberShakeSiteRegionses = cyberShakeSiteRegionses;
	}

	public Set<PeakAmplitudes> getPeakAmplitudeses() {
		return this.peakAmplitudeses;
	}

	public void setPeakAmplitudeses(Set<PeakAmplitudes> peakAmplitudeses) {
		this.peakAmplitudeses = peakAmplitudeses;
	}
	
	public String toString() {
		return "CS_Site_Name: " + this.csSiteName + 
					" , CS_Site_ID: " + this.csSiteId +
					" , CS_Short_Name: " + this.csShortName +
					" , CS_Site_Lat: " + this.csSiteLat +
					" , CS_Site_Lon: " + this.csSiteLon;
	}

}
