package mapping;

// Generated Aug 9, 2007 9:53:47 PM by Hibernate Tools 3.2.0.b9

/**
 * ErfMetadata generated by hbm2java
 */
public class ErfMetadata implements java.io.Serializable {

	private ErfMetadataId id;

	private ErfIds erfIds;

	private String erfAttrType;

	private String erfAttrUnits;

	public ErfMetadata() {
	}

	public ErfMetadata(ErfMetadataId id, ErfIds erfIds) {
		this.id = id;
		this.erfIds = erfIds;
	}

	public ErfMetadata(ErfMetadataId id, ErfIds erfIds, String erfAttrType,
			String erfAttrUnits) {
		this.id = id;
		this.erfIds = erfIds;
		this.erfAttrType = erfAttrType;
		this.erfAttrUnits = erfAttrUnits;
	}

	public ErfMetadataId getId() {
		return this.id;
	}

	public void setId(ErfMetadataId id) {
		this.id = id;
	}

	public ErfIds getErfIds() {
		return this.erfIds;
	}

	public void setErfIds(ErfIds erfIds) {
		this.erfIds = erfIds;
	}

	public String getErfAttrType() {
		return this.erfAttrType;
	}

	public void setErfAttrType(String erfAttrType) {
		this.erfAttrType = erfAttrType;
	}

	public String getErfAttrUnits() {
		return this.erfAttrUnits;
	}

	public void setErfAttrUnits(String erfAttrUnits) {
		this.erfAttrUnits = erfAttrUnits;
	}

}
