package mapping;

// Generated Aug 9, 2007 9:53:47 PM by Hibernate Tools 3.2.0.b9

/**
 * ErfMetadataId generated by hbm2java
 */
public class ErfMetadataId implements java.io.Serializable {

	private int erfId;

	private String erfAttrName;

	private String erfAttrValue;

	public ErfMetadataId() {
	}

	public ErfMetadataId(int erfId, String erfAttrName, String erfAttrValue) {
		this.erfId = erfId;
		this.erfAttrName = erfAttrName;
		this.erfAttrValue = erfAttrValue;
	}

	public int getErfId() {
		return this.erfId;
	}

	public void setErfId(int erfId) {
		this.erfId = erfId;
	}

	public String getErfAttrName() {
		return this.erfAttrName;
	}

	public void setErfAttrName(String erfAttrName) {
		this.erfAttrName = erfAttrName;
	}

	public String getErfAttrValue() {
		return this.erfAttrValue;
	}

	public void setErfAttrValue(String erfAttrValue) {
		this.erfAttrValue = erfAttrValue;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ErfMetadataId))
			return false;
		ErfMetadataId castOther = (ErfMetadataId) other;

		return (this.getErfId() == castOther.getErfId())
				&& ((this.getErfAttrName() == castOther.getErfAttrName()) || (this
						.getErfAttrName() != null
						&& castOther.getErfAttrName() != null && this
						.getErfAttrName().equals(castOther.getErfAttrName())))
				&& ((this.getErfAttrValue() == castOther.getErfAttrValue()) || (this
						.getErfAttrValue() != null
						&& castOther.getErfAttrValue() != null && this
						.getErfAttrValue().equals(castOther.getErfAttrValue())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getErfId();
		result = 37
				* result
				+ (getErfAttrName() == null ? 0 : this.getErfAttrName()
						.hashCode());
		result = 37
				* result
				+ (getErfAttrValue() == null ? 0 : this.getErfAttrValue()
						.hashCode());
		return result;
	}

}
