package mapping;

// Generated Aug 9, 2007 9:53:47 PM by Hibernate Tools 3.2.0.b9

/**
 * OpenShaCyberShakeInterfaces generated by hbm2java
 */
public class OpenShaCyberShakeInterfaces implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 913897347171870797L;
	private OpenShaCyberShakeInterfacesId id;

	public OpenShaCyberShakeInterfaces() {
	}

	public OpenShaCyberShakeInterfaces(OpenShaCyberShakeInterfacesId id) {
		this.id = id;
	}

	public OpenShaCyberShakeInterfacesId getId() {
		return this.id;
	}

	public void setId(OpenShaCyberShakeInterfacesId id) {
		this.id = id;
	}

}
