package mapping;

// Generated Aug 9, 2007 9:53:47 PM by Hibernate Tools 3.2.0.b9

/**
 * OpenShaCyberShakeInterfacesId generated by hbm2java
 */
public class OpenShaCyberShakeInterfacesId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1913689739789213717L;

	private int interfaceId;

	private int interfaceMajorVersion;

	private int interfaceMinorVersion;

	private int interfaceBugfixVersion;

	public OpenShaCyberShakeInterfacesId() {
	}

	public OpenShaCyberShakeInterfacesId(int interfaceId,
			int interfaceMajorVersion, int interfaceMinorVersion,
			int interfaceBugfixVersion) {
		this.interfaceId = interfaceId;
		this.interfaceMajorVersion = interfaceMajorVersion;
		this.interfaceMinorVersion = interfaceMinorVersion;
		this.interfaceBugfixVersion = interfaceBugfixVersion;
	}

	public int getInterfaceId() {
		return this.interfaceId;
	}

	public void setInterfaceId(int interfaceId) {
		this.interfaceId = interfaceId;
	}

	public int getInterfaceMajorVersion() {
		return this.interfaceMajorVersion;
	}

	public void setInterfaceMajorVersion(int interfaceMajorVersion) {
		this.interfaceMajorVersion = interfaceMajorVersion;
	}

	public int getInterfaceMinorVersion() {
		return this.interfaceMinorVersion;
	}

	public void setInterfaceMinorVersion(int interfaceMinorVersion) {
		this.interfaceMinorVersion = interfaceMinorVersion;
	}

	public int getInterfaceBugfixVersion() {
		return this.interfaceBugfixVersion;
	}

	public void setInterfaceBugfixVersion(int interfaceBugfixVersion) {
		this.interfaceBugfixVersion = interfaceBugfixVersion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OpenShaCyberShakeInterfacesId))
			return false;
		OpenShaCyberShakeInterfacesId castOther = (OpenShaCyberShakeInterfacesId) other;

		return (this.getInterfaceId() == castOther.getInterfaceId())
				&& (this.getInterfaceMajorVersion() == castOther
						.getInterfaceMajorVersion())
				&& (this.getInterfaceMinorVersion() == castOther
						.getInterfaceMinorVersion())
				&& (this.getInterfaceBugfixVersion() == castOther
						.getInterfaceBugfixVersion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getInterfaceId();
		result = 37 * result + this.getInterfaceMajorVersion();
		result = 37 * result + this.getInterfaceMinorVersion();
		result = 37 * result + this.getInterfaceBugfixVersion();
		return result;
	}

}
