package mapping;

// Generated Aug 9, 2007 9:53:47 PM by Hibernate Tools 3.2.0.b9

/**
 * PeakAmplitudes generated by hbm2java
 */
public class PeakAmplitudes implements java.io.Serializable {

	private PeakAmplitudesId id;

	private RuptureVariations ruptureVariations;

	private RuptureVariationScenarioIds ruptureVariationScenarioIds;

	private ErfIds erfIds;

	private SgtVariationIds sgtVariationIds;

	private Ruptures ruptures;

	private CyberShakeSites cyberShakeSites;

	private double imValue;

	private String units;

	public PeakAmplitudes() {
	}

	public PeakAmplitudes(PeakAmplitudesId id,
			RuptureVariations ruptureVariations,
			RuptureVariationScenarioIds ruptureVariationScenarioIds,
			ErfIds erfIds, SgtVariationIds sgtVariationIds, Ruptures ruptures,
			CyberShakeSites cyberShakeSites, double imValue, String units) {
		this.id = id;
		this.ruptureVariations = ruptureVariations;
		this.ruptureVariationScenarioIds = ruptureVariationScenarioIds;
		this.erfIds = erfIds;
		this.sgtVariationIds = sgtVariationIds;
		this.ruptures = ruptures;
		this.cyberShakeSites = cyberShakeSites;
		this.imValue = imValue;
		this.units = units;
	}

	public PeakAmplitudesId getId() {
		return this.id;
	}

	public void setId(PeakAmplitudesId id) {
		this.id = id;
	}

	public RuptureVariations getRuptureVariations() {
		return this.ruptureVariations;
	}

	public void setRuptureVariations(RuptureVariations ruptureVariations) {
		this.ruptureVariations = ruptureVariations;
	}

	public RuptureVariationScenarioIds getRuptureVariationScenarioIds() {
		return this.ruptureVariationScenarioIds;
	}

	public void setRuptureVariationScenarioIds(
			RuptureVariationScenarioIds ruptureVariationScenarioIds) {
		this.ruptureVariationScenarioIds = ruptureVariationScenarioIds;
	}

	public ErfIds getErfIds() {
		return this.erfIds;
	}

	public void setErfIds(ErfIds erfIds) {
		this.erfIds = erfIds;
	}

	public SgtVariationIds getSgtVariationIds() {
		return this.sgtVariationIds;
	}

	public void setSgtVariationIds(SgtVariationIds sgtVariationIds) {
		this.sgtVariationIds = sgtVariationIds;
	}

	public Ruptures getRuptures() {
		return this.ruptures;
	}

	public void setRuptures(Ruptures ruptures) {
		this.ruptures = ruptures;
	}

	public CyberShakeSites getCyberShakeSites() {
		return this.cyberShakeSites;
	}

	public void setCyberShakeSites(CyberShakeSites cyberShakeSites) {
		this.cyberShakeSites = cyberShakeSites;
	}

	public double getImValue() {
		return this.imValue;
	}

	public void setImValue(double imValue) {
		this.imValue = imValue;
	}

	public String getUnits() {
		return this.units;
	}

	public void setUnits(String units) {
		this.units = units;
	}

}
