package mapping;

// Generated Aug 9, 2007 12:19:41 AM by Hibernate Tools 3.2.0.b9

/**
 * PeakAmplitudes generated by hbm2java
 */
public class PeakAmplitudes implements java.io.Serializable {

	private PeakAmplitudesId id;

	private double imValue;

	private String units;

	public PeakAmplitudes() {
	}

	public PeakAmplitudes(PeakAmplitudesId id, double imValue, String units) {
		this.id = id;
		this.imValue = imValue;
		this.units = units;
	}

	public PeakAmplitudesId getId() {
		return this.id;
	}

	public void setId(PeakAmplitudesId id) {
		this.id = id;
	}

	public double getImValue() {
		return this.imValue;
	}

	public void setImValue(double imValue) {
		this.imValue = imValue;
	}

	public String getUnits() {
		return this.units;
	}

	public void setUnits(String units) {
		this.units = units;
	}

}
