package mapping;

// Generated Aug 9, 2007 9:53:47 PM by Hibernate Tools 3.2.0.b9

/**
 * RuptureVariationScenarioMetadata generated by hbm2java
 */
public class RuptureVariationScenarioMetadata implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7162027495072042405L;

	private RuptureVariationScenarioMetadataId id;

	private RuptureVariationScenarioIds ruptureVariationScenarioIds;

	private String rupVarScenarioAttrType;

	private String rupVarScenarioAttrUnits;

	public RuptureVariationScenarioMetadata() {
	}

	public RuptureVariationScenarioMetadata(
			RuptureVariationScenarioMetadataId id,
			RuptureVariationScenarioIds ruptureVariationScenarioIds,
			String rupVarScenarioAttrType) {
		this.id = id;
		this.ruptureVariationScenarioIds = ruptureVariationScenarioIds;
		this.rupVarScenarioAttrType = rupVarScenarioAttrType;
	}

	public RuptureVariationScenarioMetadata(
			RuptureVariationScenarioMetadataId id,
			RuptureVariationScenarioIds ruptureVariationScenarioIds,
			String rupVarScenarioAttrType, String rupVarScenarioAttrUnits) {
		this.id = id;
		this.ruptureVariationScenarioIds = ruptureVariationScenarioIds;
		this.rupVarScenarioAttrType = rupVarScenarioAttrType;
		this.rupVarScenarioAttrUnits = rupVarScenarioAttrUnits;
	}

	public RuptureVariationScenarioMetadataId getId() {
		return this.id;
	}

	public void setId(RuptureVariationScenarioMetadataId id) {
		this.id = id;
	}

	public RuptureVariationScenarioIds getRuptureVariationScenarioIds() {
		return this.ruptureVariationScenarioIds;
	}

	public void setRuptureVariationScenarioIds(
			RuptureVariationScenarioIds ruptureVariationScenarioIds) {
		this.ruptureVariationScenarioIds = ruptureVariationScenarioIds;
	}

	public String getRupVarScenarioAttrType() {
		return this.rupVarScenarioAttrType;
	}

	public void setRupVarScenarioAttrType(String rupVarScenarioAttrType) {
		this.rupVarScenarioAttrType = rupVarScenarioAttrType;
	}

	public String getRupVarScenarioAttrUnits() {
		return this.rupVarScenarioAttrUnits;
	}

	public void setRupVarScenarioAttrUnits(String rupVarScenarioAttrUnits) {
		this.rupVarScenarioAttrUnits = rupVarScenarioAttrUnits;
	}

}
