package mapping;

// Generated Aug 9, 2007 9:53:47 PM by Hibernate Tools 3.2.0.b9

/**
 * RuptureVariationScenarioMetadataId generated by hbm2java
 */
public class RuptureVariationScenarioMetadataId implements java.io.Serializable {

	private int rupVarScenarioId;

	private String rupVarScenarioAttrName;

	private String rupVarScenarioAttrValue;

	public RuptureVariationScenarioMetadataId() {
	}

	public RuptureVariationScenarioMetadataId(int rupVarScenarioId,
			String rupVarScenarioAttrName, String rupVarScenarioAttrValue) {
		this.rupVarScenarioId = rupVarScenarioId;
		this.rupVarScenarioAttrName = rupVarScenarioAttrName;
		this.rupVarScenarioAttrValue = rupVarScenarioAttrValue;
	}

	public int getRupVarScenarioId() {
		return this.rupVarScenarioId;
	}

	public void setRupVarScenarioId(int rupVarScenarioId) {
		this.rupVarScenarioId = rupVarScenarioId;
	}

	public String getRupVarScenarioAttrName() {
		return this.rupVarScenarioAttrName;
	}

	public void setRupVarScenarioAttrName(String rupVarScenarioAttrName) {
		this.rupVarScenarioAttrName = rupVarScenarioAttrName;
	}

	public String getRupVarScenarioAttrValue() {
		return this.rupVarScenarioAttrValue;
	}

	public void setRupVarScenarioAttrValue(String rupVarScenarioAttrValue) {
		this.rupVarScenarioAttrValue = rupVarScenarioAttrValue;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RuptureVariationScenarioMetadataId))
			return false;
		RuptureVariationScenarioMetadataId castOther = (RuptureVariationScenarioMetadataId) other;

		return (this.getRupVarScenarioId() == castOther.getRupVarScenarioId())
				&& ((this.getRupVarScenarioAttrName() == castOther
						.getRupVarScenarioAttrName()) || (this
						.getRupVarScenarioAttrName() != null
						&& castOther.getRupVarScenarioAttrName() != null && this
						.getRupVarScenarioAttrName().equals(
								castOther.getRupVarScenarioAttrName())))
				&& ((this.getRupVarScenarioAttrValue() == castOther
						.getRupVarScenarioAttrValue()) || (this
						.getRupVarScenarioAttrValue() != null
						&& castOther.getRupVarScenarioAttrValue() != null && this
						.getRupVarScenarioAttrValue().equals(
								castOther.getRupVarScenarioAttrValue())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRupVarScenarioId();
		result = 37
				* result
				+ (getRupVarScenarioAttrName() == null ? 0 : this
						.getRupVarScenarioAttrName().hashCode());
		result = 37
				* result
				+ (getRupVarScenarioAttrValue() == null ? 0 : this
						.getRupVarScenarioAttrValue().hashCode());
		return result;
	}

}
