package mapping;

// Generated Aug 9, 2007 9:53:47 PM by Hibernate Tools 3.2.0.b9

/**
 * SgtVariationMetadataId generated by hbm2java
 */
public class SgtVariationMetadataId implements java.io.Serializable {

	private int sgtVariationId;

	private String sgtVariationAttrName;

	private String sgtVariationAttrValue;

	public SgtVariationMetadataId() {
	}

	public SgtVariationMetadataId(int sgtVariationId,
			String sgtVariationAttrName, String sgtVariationAttrValue) {
		this.sgtVariationId = sgtVariationId;
		this.sgtVariationAttrName = sgtVariationAttrName;
		this.sgtVariationAttrValue = sgtVariationAttrValue;
	}

	public int getSgtVariationId() {
		return this.sgtVariationId;
	}

	public void setSgtVariationId(int sgtVariationId) {
		this.sgtVariationId = sgtVariationId;
	}

	public String getSgtVariationAttrName() {
		return this.sgtVariationAttrName;
	}

	public void setSgtVariationAttrName(String sgtVariationAttrName) {
		this.sgtVariationAttrName = sgtVariationAttrName;
	}

	public String getSgtVariationAttrValue() {
		return this.sgtVariationAttrValue;
	}

	public void setSgtVariationAttrValue(String sgtVariationAttrValue) {
		this.sgtVariationAttrValue = sgtVariationAttrValue;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SgtVariationMetadataId))
			return false;
		SgtVariationMetadataId castOther = (SgtVariationMetadataId) other;

		return (this.getSgtVariationId() == castOther.getSgtVariationId())
				&& ((this.getSgtVariationAttrName() == castOther
						.getSgtVariationAttrName()) || (this
						.getSgtVariationAttrName() != null
						&& castOther.getSgtVariationAttrName() != null && this
						.getSgtVariationAttrName().equals(
								castOther.getSgtVariationAttrName())))
				&& ((this.getSgtVariationAttrValue() == castOther
						.getSgtVariationAttrValue()) || (this
						.getSgtVariationAttrValue() != null
						&& castOther.getSgtVariationAttrValue() != null && this
						.getSgtVariationAttrValue().equals(
								castOther.getSgtVariationAttrValue())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSgtVariationId();
		result = 37
				* result
				+ (getSgtVariationAttrName() == null ? 0 : this
						.getSgtVariationAttrName().hashCode());
		result = 37
				* result
				+ (getSgtVariationAttrValue() == null ? 0 : this
						.getSgtVariationAttrValue().hashCode());
		return result;
	}

}
