package mapping;

// Generated Aug 9, 2007 9:53:47 PM by Hibernate Tools 3.2.0.b9

import java.util.HashSet;
import java.util.Set;

/**
 * SgtVariationIds generated by hbm2java
 */
public class SgtVariationIds implements java.io.Serializable {

	private int sgtVariationId;

	private ErfIds erfIds;

	private String sgtVariationName;

	private String sgtVariationDescription;

	private Set<SgtVariationMetadata> sgtVariationMetadatas = new HashSet<SgtVariationMetadata>(
			0);

	private Set<PeakAmplitudes> peakAmplitudeses = new HashSet<PeakAmplitudes>(
			0);

	public SgtVariationIds() {
	}

	public SgtVariationIds(int sgtVariationId, ErfIds erfIds,
			String sgtVariationName) {
		this.sgtVariationId = sgtVariationId;
		this.erfIds = erfIds;
		this.sgtVariationName = sgtVariationName;
	}

	public SgtVariationIds(int sgtVariationId, ErfIds erfIds,
			String sgtVariationName, String sgtVariationDescription,
			Set<SgtVariationMetadata> sgtVariationMetadatas,
			Set<PeakAmplitudes> peakAmplitudeses) {
		this.sgtVariationId = sgtVariationId;
		this.erfIds = erfIds;
		this.sgtVariationName = sgtVariationName;
		this.sgtVariationDescription = sgtVariationDescription;
		this.sgtVariationMetadatas = sgtVariationMetadatas;
		this.peakAmplitudeses = peakAmplitudeses;
	}

	public int getSgtVariationId() {
		return this.sgtVariationId;
	}

	public void setSgtVariationId(int sgtVariationId) {
		this.sgtVariationId = sgtVariationId;
	}

	public ErfIds getErfIds() {
		return this.erfIds;
	}

	public void setErfIds(ErfIds erfIds) {
		this.erfIds = erfIds;
	}

	public String getSgtVariationName() {
		return this.sgtVariationName;
	}

	public void setSgtVariationName(String sgtVariationName) {
		this.sgtVariationName = sgtVariationName;
	}

	public String getSgtVariationDescription() {
		return this.sgtVariationDescription;
	}

	public void setSgtVariationDescription(String sgtVariationDescription) {
		this.sgtVariationDescription = sgtVariationDescription;
	}

	public Set<SgtVariationMetadata> getSgtVariationMetadatas() {
		return this.sgtVariationMetadatas;
	}

	public void setSgtVariationMetadatas(
			Set<SgtVariationMetadata> sgtVariationMetadatas) {
		this.sgtVariationMetadatas = sgtVariationMetadatas;
	}

	public Set<PeakAmplitudes> getPeakAmplitudeses() {
		return this.peakAmplitudeses;
	}

	public void setPeakAmplitudeses(Set<PeakAmplitudes> peakAmplitudeses) {
		this.peakAmplitudeses = peakAmplitudeses;
	}

}
