generate_rvfrac: generate_rvfrac.c
	gcc -o generate_rvfrac generate_rvfrac.c -L/gpfs/alpine/proj-shared/geo112/CyberShake/software/RuptureCodes/RupGen-api-5.4.2/lib -lrupgen -I/gpfs/alpine/proj-shared/geo112/CyberShake/software/RuptureCodes/RupGen-api-5.4.2/include -lpython2.7 -I/usr/include/python2.7/ -lm -L${OLCF_FFTW_ROOT}/lib -lfftw3f -L/gpfs/alpine/proj-shared/geo112/CyberShake/utils/libmemcached_1.0.18/lib -lmemcached -L../../Getpar/getpar/lib -lget

generate_seeds: generate_seeds.c
	gcc -o generate_seeds generate_seeds.c -L/gpfs/alpine/proj-shared/geo112/CyberShake/software/RuptureCodes/RupGen-api-5.4.2/lib -lrupgen -I/gpfs/alpine/proj-shared/geo112/CyberShake/software/RuptureCodes/RupGen-api-5.4.2/include -lpython2.7 -I/usr/include/python2.7/ -lm -L${OLCF_FFTW_ROOT}/lib -lfftw3f -L/gpfs/alpine/proj-shared/geo112/CyberShake/utils/libmemcached_1.0.18/lib -lmemcached -L../../Getpar/getpar/lib -lget
